project:
  type: website

website:
  title: "jsalv webapps"
  search: false
  navbar:
    tools:
      - icon: github
        href: https://github.com/jsal13/
      - icon: controller
        href: https://melat0nin.itch.io/
  sidebar:
    style: "docked"
    contents:
      - section: "Music"
        contents:
          - ./interval-training/index.qmd

format:
  html:
    theme:
      light: cosmo
      dark: cyborg
    css: styles.css
    # toc: true
